import pygame
import sys
from Gamestate import Gamestate
from Move import Move

BOARD_WIDTH = 512
BOARD_HEIGHT = 512
MOVE_LOG_PANEL_WIDTH = 250
MOVE_LOG_PANEL_HEIGHT = BOARD_HEIGHT
WINDOW_WIDTH = BOARD_WIDTH + MOVE_LOG_PANEL_WIDTH
WINDOW_HEIGHT = BOARD_HEIGHT
DIMENSION = 8
SQ_SIZE = BOARD_WIDTH // DIMENSION
MAX_FPS = 60
IMAGES = {}

def load_images():
    pieces = ['wp', 'wR', 'wN', 'wB', 'wQ', 'wK', 'bp', 'bR', 'bN', 'bB', 'bQ', 'bK']
    for piece in pieces:
        IMAGES[piece] = pygame.transform.scale(
            pygame.image.load("images/" + piece + ".png"), 
            (SQ_SIZE, SQ_SIZE)
        )

def main():
    pygame.init()
    screen = pygame.display.set_mode((WINDOW_WIDTH, WINDOW_HEIGHT))
    pygame.display.set_caption("Chess Game v1.0")
    clock = pygame.time.Clock()
    
    gs = Gamestate()

    load_images()

    sq_selected = ()
    player_clicks = []

    legal_moves = gs.get_all_legal_moves()
    move_made = False
    running = True
    while running:
        for event in pygame.event.get():
            if event.type == pygame.QUIT:
                running = False

            elif event.type == pygame.MOUSEBUTTONDOWN:
                location = pygame.mouse.get_pos()
                col = location[0] // SQ_SIZE
                row = location[1] // SQ_SIZE

                #Show the legal moves for a selected piece
                if sq_selected != (row, col) and gs.board[row][col] and gs.board[row][col].color == ('White' if gs.white_to_move else 'Black'):
                    sq_selected = (row, col)
                    player_clicks = [sq_selected]
                #Hide them if they click the same piece again
                elif sq_selected == (row, col):
                    sq_selected = ()
                    player_clicks = []
                else:
                    sq_selected = (row, col)
                    player_clicks.append(sq_selected)

                if len(player_clicks) == 2:
                    #If the user clicked a piece and then a square, make that a move and see if it has the same squares as any legal move
                    #Instead of just making the temp move, we make the move generated by get_all_legal_moves, since it handles castling, promotion, & ep correctly
                    temp_move = Move(player_clicks[0], player_clicks[1], gs.board)
                    candidate_moves = [move for move in legal_moves if move == temp_move]
                    chosen_move = None
                    if len(candidate_moves) == 1:
                        chosen_move = candidate_moves[0]
                    elif len(candidate_moves) > 1:
                        promote_to = get_user_promotion_choice()
                        for move in candidate_moves:
                            if promote_to == move.promote_to:
                                chosen_move = move

                    if chosen_move is not None:
                        gs.make_move(chosen_move)
                        move_made = True
                        sq_selected = ()
                        player_clicks = []
                        for move in legal_moves:
                            print(move.get_algebraic_notation())
                    else:
                        player_clicks = []
                        sq_selected = ()
            elif event.type == pygame.KEYDOWN:
                if event.key == pygame.K_z:
                    gs.undo_move()
                    move_made = True
        
                    
        if move_made:
            legal_moves = gs.get_all_legal_moves()
            move_made = False
                
        draw_game_state(screen, gs, legal_moves, sq_selected)
        clock.tick(MAX_FPS)
        pygame.display.flip()

    pygame.quit()
    sys.exit()

def draw_game_state(screen, gs, legal_moves, sq_selected):
    draw_board(screen)
    highlight_squares(screen, gs, legal_moves, sq_selected)
    draw_pieces(screen, gs.board)

    move_log_font = pygame.font.SysFont("Arial", 18, False, False)
    draw_move_log(screen, gs, move_log_font)

def draw_move_log(screen, gs, font):
    move_log_rect = pygame.Rect(
        BOARD_WIDTH, 0, MOVE_LOG_PANEL_WIDTH, MOVE_LOG_PANEL_HEIGHT
    )
    pygame.draw.rect(screen, pygame.Color("black"), move_log_rect)\
    
    move_log = gs.move_log
    move_text_log = []
    moves_to_show = 88 #Current hardcoded window and font sizes allow 44 move pairs to render
    start_index = max(0, len(move_log) - moves_to_show)
    if start_index % 2 != 0:
        start_index += 1 #This ensures white's moves are always displayed on the left side of the move pair

    for i in range(start_index, len(move_log), 2):
        move_string = f"{i // 2 + 1}. {move_log[i].get_algebraic_notation()} "

        if i + 1 < len(move_log): #If black has an accompanying move, print that as well
            move_string += f"{move_log[i+1].get_algebraic_notation()}"

        move_text_log.append(move_string)

    padding = 5
    text_y = padding
    line_spacing = 2
    text_object = font.render("Move Log", True, pygame.Color("white"))

    for i in range(len(move_text_log)):
        text = move_text_log[i]
        text_object = font.render(text, True, pygame.Color("white"))
        
        text_location = move_log_rect.move(padding, text_y)
        screen.blit(text_object, text_location)
        
        text_y += text_object.get_height() + line_spacing

        if text_y >= MOVE_LOG_PANEL_HEIGHT - 20: 
             text_y = padding
             move_log_rect.x += 120
     
def draw_board(screen):
    colors = [pygame.Color("gray"), pygame.Color("gray25")]
    for r in range(DIMENSION):
        for c in range(DIMENSION):
            color = colors[((r + c) % 2)]
            pygame.draw.rect(screen, color, pygame.Rect(c*SQ_SIZE, r*SQ_SIZE, SQ_SIZE, SQ_SIZE))

def draw_pieces(screen, board):
    for r in range(DIMENSION):
        for c in range(DIMENSION):
            piece = board[r][c]
            if piece is not None:
                piece_name = str(piece) 
                
                screen.blit(IMAGES[piece_name], pygame.Rect(c*SQ_SIZE, r*SQ_SIZE, SQ_SIZE, SQ_SIZE))

def highlight_squares(screen, gs, legal_moves, sq_selected):
    if sq_selected != ():
        row, col = sq_selected
        
        if gs.board[row][col] and gs.board[row][col].color == ('White' if gs.white_to_move else 'Black'):
            
            # Highlight the selected square
            s = pygame.Surface((SQ_SIZE, SQ_SIZE))
            s.set_alpha(100) # Transparency: 0 = transparent, 255 = opaque
            s.fill(pygame.Color('darkgreen'))
            screen.blit(s, (col*SQ_SIZE, row*SQ_SIZE))
            
            # Highlight moves from that square
            s.fill(pygame.Color('yellow'))
            for move in legal_moves:
                if move.start_row == row and move.start_col == col:
                    screen.blit(s, (move.end_col*SQ_SIZE, move.end_row*SQ_SIZE))

def get_user_promotion_choice():
    print("Pawn Promotion! Choose a piece:")
    print("Q = Queen, R = Rook, B = Bishop, N = Knight")
    
    valid_choices = {'Q': 'Queen', 'R': 'Rook', 'B': 'Bishop', 'N': 'Knight'}
    
    while True:
        choice = input("Enter choice (Q/R/B/N): ").strip().upper()
        if choice in valid_choices:
            print(choice)
            return choice 
        print(f"'{choice}' is invalid. Please enter Q, R, B, or N.")

if __name__ == "__main__":
    main()